name: unit test

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  unit_test:
    name: flutter test
    runs-on: ubuntu-latest
    steps:
      - name: set up repository
        uses: actions/checkout@v2
      - name: set up java
        uses: actions/setup-java@v1
        with:
          java-version: "13.x"
      - name: restore cache
        uses: actions/cache@v2
        with:
          path: |
            .packages
          key: ${{ runner.os }}-${{ hashFiles('pubspec.lock') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('pubspec.lock') }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.5.0"
      - name: flutter pub get
        run: flutter pub get
      - name: flutter test
        run: flutter test --machine > test.json
      - name: flutter coverage
        run: flutter test --coverage
        if: success() || failure()
      - uses: ueki-tomohiro/flutter-result-tool@v1
        with:
          machinePath: test.json
          coveragePath: coverage/lcov.info
        if: success() || failure()
